repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.7.0
    hooks:
      - id: zizmor
