name: "Install Kubeconform"
description: "Installs a specific version of Kubeconform"

inputs:
  version:
    description: "Version of Kubeconform to install"
    required: true
    default: "0.7.0"

  arch:
    description: "Target architecture (e.g. X64, ARM64, ARM, IA32)"
    required: false
    default: "${{ runner.arch }}"

  os:
    description: "Target operating system (e.g. Linux, Windows, macOS)"
    required: false
    default: "${{ runner.os }}"

  sha256:
    description: "SHA256 checksum to verify the downloaded tarball"
    required: true

  install-dir:
    description: "Directory to install Kubeconform"
    required: false
    default: "/usr/local/bin"

  github-token:
    description: "GitHub token for authentication"
    required: false
    default: "${{ github.token }}"

runs:
  using: "composite"
  steps:
    - name: Cache Kubeconform
      id: cache
      uses: actions/cache@v4
      with:
        path: artifact.tar.gz
        key: kubeconform-${{ inputs.version }}-${{ inputs.arch }}-${{ inputs.sha256 }}

    - name: Download Kubeconform release asset
      if: steps.cache.outputs.cache-hit != 'true'
      id: download-kubeconform
      shell: bash
      env:
        _ARCH: "${{ inputs.arch }}"
        _OS: "${{ inputs.os }}"
        _VERSION: "${{ inputs.version }}"
        _INSTALL_DIR: "${{ inputs.install-dir }}"
        _SHA256: "${{ inputs.sha256 }}"
        GH_TOKEN: "${{ inputs.github-token }}"
      run: |
        ${{ github.action_path }}/../../../scripts/download.py \
          --arch "${_ARCH}" \
          --os "${_OS}" \
          --version "${_VERSION}" \
          --file "artifact.tar.gz" \
          --sha256 "${_SHA256}" \
          --github-token "${GH_TOKEN}" \
          --repo "yannh/kubeconform" \
          --pattern "kubeconform-{os}-{arch}.tar.gz" \
          --map-arch X64=amd64 \
          --map-arch IA32=386 \
          --map-arch ARM=armv6 \
          --map-arch ARM64=arm64 \
          --map-os Linux=linux \
          --map-os Windows=windows \
          --map-os macOS=darwin

    - name: Install Kubeconform
      shell: bash
      env:
        _INSTALL_DIR: "${{ inputs.install-dir }}"
      run: |
        TEMP_DIR=$(mktemp -d)
        tar -xzf artifact.tar.gz -C "${TEMP_DIR}"

        mkdir -p "${_INSTALL_DIR}"
        chmod +x "${TEMP_DIR}/kubeconform"
        mv -f "${TEMP_DIR}/kubeconform" "${_INSTALL_DIR}/kubeconform"

    - name: Verify installation
      shell: bash
      run: |
        command -v kubeconform
