name: "Install Proto"
description: "Installs a specific version of Proto CLI"

inputs:
  version:
    description: "Version of Proto to install"
    required: true

  arch:
    description: "Target architecture (e.g. X64, ARM64)"
    required: false
    default: "${{ runner.arch }}"

  os:
    description: "Target operating system (e.g. Linux, Windows, macOS)"
    required: false
    default: "${{ runner.os }}"

  sha256:
    description: "SHA256 checksum to verify the downloaded artifact"
    required: true

  install-dir:
    description: "Directory to install Proto"
    required: false
    default: "${{ runner.temp }}/bin"

  github-token:
    description: "GitHub token for authentication"
    required: false
    default: "${{ github.token }}"

runs:
  using: "composite"
  steps:
    - name: Restore cache
      id: restore
      uses: actions/cache@v4
      with:
        path: proto_cli-${{ inputs.arch }}-${{ inputs.os }}.tar.xz
        key: proto-${{ inputs.version }}-${{ inputs.arch }}-${{ inputs.sha256 }}

    - name: Download Proto release asset
      id: download
      shell: python
      env:
        PYTHONPATH: "${{ github.action_path }}/../../.."
        OS: "${{ inputs.os }}"
        ARCH: "${{ inputs.arch }}"
        VERSION: "${{ inputs.version }}"
        FILE: "proto_cli-${{ inputs.arch }}-${{ inputs.os }}.tar.xz"
        SHA256: "${{ inputs.sha256 }}"
        GITHUB_TOKEN: "${{ inputs.github-token }}"
      run: |
        from setup_everything.download.download import download_from_env

        download_from_env("manifests/proto/manifest.json")

    - name: Install Proto
      shell: python
      env:
        PYTHONPATH: "${{ github.action_path }}/../../.."
        FILE: "proto_cli-${{ inputs.arch }}-${{ inputs.os }}.tar.xz"
        NAME: ${{ steps.download.outputs.filename }}
        INSTALL_DIR: "${{ inputs.install-dir }}"
      run: |
        from setup_everything.install.install import install_from_env

        install_from_env("manifests/proto/manifest.json")

    - name: Verify installation
      shell: bash
      run: |
        command -v proto
