name: "Install Proto"
description: "Installs a specific version of Proto CLI"

inputs:
  version:
    description: "Version of Proto to install"
    required: true

  arch:
    description: "Target architecture (e.g. X64, ARM64)"
    required: false
    default: "${{ runner.arch }}"

  os:
    description: "Target operating system (e.g. Linux, Windows, macOS)"
    required: false
    default: "${{ runner.os }}"

  sha256:
    description: "SHA256 checksum to verify the downloaded archive"
    required: true

  install-dir:
    description: "Directory to install Proto"
    required: false
    default: "/usr/local/bin"

  github-token:
    description: "GitHub token for authentication"
    required: false
    default: "${{ github.token }}"

runs:
  using: "composite"
  steps:
    - name: Cache Proto
      id: cache
      uses: actions/cache@v4
      with:
        path: artifact.tar.xz
        key: proto-${{ inputs.version }}-${{ inputs.arch }}-${{ inputs.sha256 }}

    - name: Download Proto release asset
      if: steps.cache.outputs.cache-hit != 'true'
      id: download-proto
      shell: bash
      env:
        _ARCH: "${{ inputs.arch }}"
        _OS: "${{ inputs.os }}"
        _VERSION: "${{ inputs.version }}"
        _INSTALL_DIR: "${{ inputs.install-dir }}"
        _SHA256: "${{ inputs.sha256 }}"
        GH_TOKEN: "${{ inputs.github-token }}"
      run: |
        # Download the Proto release asset
        ${{ github.action_path }}/../../../scripts/download.py \
          --arch "${_ARCH}" \
          --os "${_OS}" \
          --version "${_VERSION}" \
          --file "artifact.tar.xz" \
          --sha256 "${_SHA256}" \
          --github-token "${GH_TOKEN}" \
          --repo "moonrepo/proto" \
          --pattern "proto_cli-{arch}-{os}.tar.xz" \
          --map-arch X64=x86_64 \
          --map-arch ARM64=aarch64 \
          --map-os Linux=unknown-linux-gnu \
          --map-os macOS=apple-darwin \
          --map-os Windows=pc-windows-msvc

    - name: Install Proto
      shell: bash
      env:
        _INSTALL_DIR: "${{ inputs.install-dir }}"
      run: |
        TEMP_DIR=$(mktemp -d)
        tar --strip-components=1 -xf artifact.tar.xz -C "${TEMP_DIR}"

        mkdir -p "${_INSTALL_DIR}"
        chmod +x "${TEMP_DIR}/proto"
        mv -f "${TEMP_DIR}/proto" "${_INSTALL_DIR}/proto"

    - name: Verify installation
      shell: bash
      run: |
        command -v proto
