name: "Install Trivy"
description: "Installs a specific version of Trivy"

inputs:
  version:
    description: "Version of Trivy to install"
    required: true
    default: "0.62.1"

  arch:
    description: "Target architecture (e.g. X64, ARM64, ARM, IA32)"
    required: false
    default: "${{ runner.arch }}"

  os:
    description: "Target operating system (e.g. Linux, Windows, macOS)"
    required: false
    default: "${{ runner.os }}"

  sha256:
    description: "SHA256 checksum to verify the downloaded tarball"
    required: true

  install-dir:
    description: "Directory to install Trivy"
    required: false
    default: "/usr/local/bin"

  github-token:
    description: "GitHub token for authentication"
    required: false
    default: "${{ github.token }}"

runs:
  using: "composite"
  steps:
    - name: Cache Trivy
      id: cache
      uses: actions/cache@v4
      with:
        path: artifact.tar.gz
        key: trivy-${{ inputs.version }}-${{ inputs.arch }}-${{ inputs.sha256 }}

    - name: Download Trivy release asset
      if: steps.cache.outputs.cache-hit != 'true'
      id: download-trivy
      shell: bash
      env:
        _ARCH: "${{ inputs.arch }}"
        _OS: "${{ inputs.os }}"
        _VERSION: "${{ inputs.version }}"
        _INSTALL_DIR: "${{ inputs.install-dir }}"
        _SHA256: "${{ inputs.sha256 }}"
        GH_TOKEN: "${{ inputs.github-token }}"
      run: |
        ./scripts/download.py \
          --arch "${_ARCH}" \
          --os "${_OS}" \
          --version "${_VERSION}" \
          --file "artifact.tar.gz" \
          --sha256 "${_SHA256}" \
          --github-token "${GH_TOKEN}" \
          --repo "aquasecurity/trivy" \
          --pattern "trivy_{version}_{os}-{arch}.tar.gz" \
          --map-arch X64=64bit \
          --map-arch IA32=32bit \
          --map-arch ARM=ARM \
          --map-arch ARM64=ARM64 \
          --map-os Windows=windows

    - name: Install Trivy
      shell: bash
      run: |
        mkdir -p "${{ inputs.install-dir }}"
        TEMP_DIR=$(mktemp -d)
        tar -xzf artifact.tar.gz -C "${TEMP_DIR}"
        chmod +x "${TEMP_DIR}/trivy"
        mv -f "${TEMP_DIR}/trivy" "${{ inputs.install-dir }}/trivy"

    - name: Verify installation
      shell: bash
      run: command -v trivy
