name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: bullfrogsec/bullfrog@dcde5841b19b7ef693224207a7fdec67fce604db # v0.8.3
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6
      - uses: jdx/mise-action@v2
