name: Setup Hugo

permissions: {}

on:
  workflow_dispatch:

jobs:
  setup-hugo:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: X64
            sha256: 294d995bd3bdcbb88d851fee61213322a53aa474125c0a6b09262e9c648cc83d
          - os: macos-latest
            arch: universal
            sha256: e2801e5fa8fe2406fb63b2dbf554ef51f79635e1bf6e13fcd1259967554ecedb

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Hugo
        uses: ./.github/actions/setup-hugo
        with:
          version: 0.147.3
          arch: ${{ matrix.arch }}
          sha256: ${{ matrix.sha256 }}

      - name: Verify Hugo installation
        shell: bash
        run: |
          hugo version
