name: Setup Kubeconform

permissions: {}

on:
  workflow_dispatch:

jobs:
  setup-kubeconform-linux-x64:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Kubeconform (X64)
        uses: ./.github/actions/setup-kubeconform
        with:
          version: 0.7.0
          arch: X64
          sha256: c31518ddd122663b3f3aa874cfe8178cb0988de944f29c74a0b9260920d115d3

  setup-kubeconform-linux-arm64:
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Kubeconform (ARM64)
        uses: ./.github/actions/setup-kubeconform
        with:
          version: 0.7.0
          arch: ARM64
          sha256: cc907ccf9e3c34523f0f32b69745265e0a6908ca85b92f41931d4537860eb83c

  setup-kubeconform-windows:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Kubeconform (X64)
        uses: ./.github/actions/setup-kubeconform
        with:
          version: 0.7.0
          arch: X64
          sha256: 9cb75551d81c909c2241ab383ced2be68363b5bfb15fd989badcc5a63bea5d7e

  setup-kubeconform-macos-arm64:
    runs-on: macos-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Kubeconform (ARM64)
        uses: ./.github/actions/setup-kubeconform
        with:
          version: 0.7.0
          arch: ARM64
          sha256: b5d32b2cb77f9c781c976b20a85e2d0bc8f9184d5d1cfe665a2f31a19f99eeb9

