name: Setup chart-testing

permissions: {}

on:
  workflow_dispatch:

jobs:
  setup-chart-testing-linux-x64:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup ct (X64)
        uses: ./.github/actions/setup-chart-testing
        with:
          version: 3.13.0
          arch: X64
          sha256: fcbae93a01887730054b5b0b4536b8cfbfe6010fdffccf66b8b87f5f764287d9

  setup-chart-testing-linux-arm64:
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup ct (ARM64)
        uses: ./.github/actions/setup-chart-testing
        with:
          version: 3.13.0
          arch: ARM64
          sha256: 281420d4d4feb498090bffe7003866e43dfe9b270c10f3573044161b28659e97

  setup-chart-testing-windows:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup ct (X64)
        uses: ./.github/actions/setup-chart-testing
        with:
          version: 3.13.0
          arch: X64
          sha256: 25a00adf758589591bbc1152b40f7286af67f9e78421ae9cc7ec2d8e962c8606

  setup-chart-testing-macos-x64:
    runs-on: macos-13

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup ct (X64)
        uses: ./.github/actions/setup-chart-testing
        with:
          version: 3.13.0
          arch: X64
          sha256: 8974f43f382511bf27ebcdf79df8d7da84391bc81723f89e9c94fa99ecdf2dea

  setup-chart-testing-macos-arm64:
    runs-on: macos-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup ct (ARM64)
        uses: ./.github/actions/setup-chart-testing
        with:
          version: 3.13.0
          arch: ARM64
          sha256: 28a9904faec853aa295bab89ee9fa43dad7d990862990ab0e8eb5aff6bdce013

